### ISSUE TITLE
How were images generated?

### ISSUE THREAD

**Issue by jacobrosenthal** [cpavlina/kicad-schlib-preview#1]

**Comment by cpavlina** [comment]
https://github.com/cpavlina/kicad-schlib/blob/master/Makefile
https://github.com/cpavlina/kicad-schlib/blob/master/scripts/schlib-render.py

**Comment by SchrodingersGat** [comment]
@cpavlina would you be opposed to the image-generation script being ported over to https://github.com/KiCad/kicad-library-utils ?

**Comment by cpavlina** [comment]
Not at all, and you have my explicit permission to relicense it however you like if it makes it easier for distribution.

Bear in mind it's a bit crusty though, I through it together in a night :P
